### ISSUE TITLE
gitignore generated folders

### ISSUE THREAD

**Issue by ppoliani** [windingtree/wt-js-libs#79]
Currently, we have several folders that are part of the repository but they can be generated on the fly. More specifically:

1. **docs**: `npm run docs-build`
2. **dist**: `npm run build`
3. **contracts** and **migrations** are part of the **wt-contract** submodule and are copied to the working directory as part of the `postinstall` npm script.  

Since there is no need to track any changes in those files, I believe it would be safe to gitignore those resources.

**Comment by AugustoL** [comment]
@ppoliani thanks for the issue! We need the `docs` folder because it is used as official documentation and we consume it from this repository, the same for the `dist` folder, it is used by the demo app. 
About the `contracts` and `migrations` folder I think they can be ignored and we can used them directly form the `wt-contracts` submodule, @adklempner do you see any problem there?

**Comment by ppoliani** [comment]
Oh ok, that makes sense. Sorry for the silly question, but could you share the links for the demo app and the official documentation?

**Comment by kvbik** [comment]
no worries, there are no silly questions ;)))

documentation link is in the `README` -> https://windingtree.github.io/wt-js-libs/ and yes, it is a github pages served from `master` branch `docs` subdir (one of the ways how you can serve them).

we do not want to link the demo site until the repository is public, but you can very easily guess it ;))) or i can share it on our rocket chat!

**Comment by kvbik** [comment]
it would be much cleaner if everything is just built, `docs` built on our `CI`, similar for `dist` it can be part of the `build` step. but so far it is just simpler/faster to have the artefacts part of the repository. i am in favor of changing it - but later. once we establish on deployment/release cycle.

**Comment by ppoliani** [comment]
@kvbik It turns out I'm not very good at guessing 😄 

Is it possible to share the link on rocket chat?

**Comment by JirkaChadima** [comment]
- dist - We've got rid of that by doing npm releases.
- contracts - We've got rid of that by using wt-contracts npm release.
- docs - This is still around since it's the easiest way of distributing the current docs right now. Since we have multiple concurrent versions at the same time (at least `master`, `proposal/next`, probably `develop` as well) and we are not sure when we will eventually merge those together, we would need a robust docs hosting supporting many versions which would ideally build the docs by itself. It's not our core priority ATM. But can be solved as a separate subproject. For now, we're just hotlinking to docs here in https://github.com/windingtree/wiki/blob/master/developer-resources.md

Closing for now, I'd recommend opening a new issue/PR considering only the **docs** part and we can move from there.
